### ISSUE TITLE
have some sort of "querylike" support

### ISSUE THREAD

**Issue by wrgr** [openconnectome/ndio#10]
Needed to allow users to pass in a "queryfile" with the parameters and service requested from a file or autogenerated list.

**Comment by wrgr** [comment]
This is required for clarity, and likely lots of other things.

**Comment by j6k4m8** [comment]
Can we consider this accomplished with the following code pattern:

``` python
query = {
    token: 'kasthuri11',
    channel: 'image',
    x_start: 1000,    x_stop: 1100,
    y_start: 1000,    y_stop: 1100,
    z_start: 1000,    z_stop: 1100,
    resolution: 3
}

oo.get_cutout(**query)
```

**Comment by j6k4m8** [comment]
@willgray I think this is a question for you

**Comment by j6k4m8** [comment]
closing...unless you have any thoughts on this?

**Comment by wrgr** [comment]
I think closing is documented by the ability to get chunks of data from a larger volume for separate (cluster) processing, like we'll want to do with Davi's data.  Agree that we are nearly there (possibly only lacking the docs)
