### ISSUE TITLE
autoingest updates

### ISSUE THREAD

**Issue by wrgr** [openconnectome/ndio#106]
Did a code review of the autoingest and ndio get/put code and found some duplication.

This issue is to more formally review code that is duplicated and integrate autoingest fully into the python package now that we have an awesome prototype.

@kunallillaney @j6k4m8 @Aeusman

**Comment by Aeusman** [comment]
@willgray Can you be more specific? I've been out for a week with essentially no contact so I'm a little out of the loop.

**Comment by j6k4m8** [comment]
@AEusman — let's talk sometime today if you're available. I think the issue
we're getting here is informative as to why some autoingest jobs are
failing as well

**Comment by Aeusman** [comment]
Im meeting with kunal at 3 in malone, if you can lets talk then, I can have class at 1:30 and 4:30, else tomorrow is good. The reason tests are failing was a server issue, I'm setting up a new test server now. The autoingest the jobs I've run so far have been successful, the majority of failure comes from lack of understanding of schema/other things

**Comment by j6k4m8** [comment]
Can't meet then, but my main take-homes are that when the test jobs were failing, the failure message simply indicated that `response` was not defined, since you were populating it in a nested scope and requesting it outside that scope, if it failed.

Sending more thoughts in a few.

**Comment by wrgr** [comment]
obe by other issues
