### ISSUE TITLE
Add clear page explaining how to get data with ndio

### ISSUE THREAD

**Issue by wrgr** [openconnectome/ndio#107]
There will eventually be 4 of these pages - get image data, get metadata, put image data, put metadata...

But for now, let's do the easiest one and explain (via text and md) how to get data both via a recommended method (with notebooks for key datasets) and via scraping to meet the needs of our users.

I'll help.

**Comment by j6k4m8** [comment]
Here's a good start (though slightly antiquated in terms of LIMS use, since now this lives entirely in the `neurodata` remote):

https://github.com/neurodata/ndio-demos/tree/master/Getting%20Started

**Comment by j6k4m8** [comment]
check it out: https://github.com/neurodata/ndio-demos/blob/master/LIMS/LIMS%20ROIs.ipynb
