### ISSUE TITLE
Add neariso endpoint

### ISSUE THREAD

**Issue by wrgr** [openconnectome/ndio#108]
Turns out we need this endpoint for a bunch of stuff.  Probably add to get_volume, but could make separate.  Will be fairly infrequent, I think.

**Comment by j6k4m8** [comment]
Can you or @kunallillaney show me where this is doc'd? Happy to add it ASAP.

**Comment by wrgr** [comment]
I can't find the docs on the website - a little help @kunallillaney?
@Aeusman

**Comment by wrgr** [comment]
"Just append neariso to call."
