### ISSUE TITLE
Confirm data endpoint for use with ndparse and all ndio out

### ISSUE THREAD

**Issue by wrgr** [openconnectome/ndio#109]
Seems to still be zyx by default - I think we agreed on xyz?

**Comment by j6k4m8** [comment]
can you clarify? I have to swap back and forth between zxy and xyz internally to treat the endpoints correctly, but all returned arrays _should_ be xyz, as far as I know.

**Comment by wrgr** [comment]
I still get zxy down with get_volume.  let's fix this today?

**Comment by j6k4m8** [comment]
Definitely.

**Comment by j6k4m8** [comment]
This is (finally!) fixed in #116!
