### ISSUE TITLE
ndio next steps

### ISSUE THREAD

**Issue by wrgr** [openconnectome/ndio#11]
### 11/12/2015 Notes
- [x] add link to demos from ndio site
- [x] sphinx build 
- [x] enumerate list of questions on tutorials
### DOD
- [ ] ndio code
  - [x] xy plane downloads 
  - [x] data cutouts with crop into ramonvolumes 
  - [x] initial version of the test suite 
  - [x] sphinx site and general homepage 
    - [x] architecture review for queries
  - [ ] id query filtered by region 
  - [x] large scale downloads
  - [x] id query 
- [ ] graphml file in disa's storage location with sufficient annotation/provenance
- [x] graph creation/parsing in CAJAL
- [x] graph retrieval in CAJAL
- [ ] graph retrieval in ndio
- [x] Object Retrieval and counting as capability validation

**Comment by j6k4m8** [comment]
these have all been broken out into their own issues. Closing this in favor of the enumerated versions!
