### ISSUE TITLE
get_token_info fails

### ISSUE THREAD

**Issue by wrgr** [openconnectome/ndio#114]
| ndio version | os | python |
| --- | --- | --- |
| 0.1.11 | macosx | 2.7 |

This command fails:

```
token = bock11
res = 6
image_size = oo.get_token_info(token)['dataset']['imagesize'][str(res)]
```

With the following message:

```
AttributeError                            Traceback (most recent call last)
<ipython-input-13-c74c03e3e0a2> in <module>()
      3 res = 6
      4 
----> 5 image_size = oo.get_token_info(token)['dataset']['imagesize'][str(res)]
      6 image_offset = oo.get_token_info(token)['dataset']['offset'][str(res)]
      7 image_res = oo.get_token_info(token)['dataset']['voxelres'][str(res)]

AttributeError: 'neurodata' object has no attribute 'get_token_info'
```

Possibly due to the new python decorators?

**Comment by j6k4m8** [comment]
`neurodata#get_token_info` has been replaced with `neurodata#get_metadata` in <kbd>0.1.11</kbd> in an effort to remove the `OCPMeta` dependency.

**Comment by wrgr** [comment]
should we use get_metadata or get_projinfo?  Either is fine - just want to understand differences.

**Comment by j6k4m8** [comment]
Right now, no difference. Do you have a preference? I want to get rid of
one eventually. (Note that there's a set_metadata as well)

**Comment by j6k4m8** [comment]
#116 fixes this!
