### ISSUE TITLE
lims ROIs name change proposal

### ISSUE THREAD

**Issue by wrgr** [openconnectome/ndio#118]
I'm pretty excited about LIMS ROIs as a concept and function.  Just realized that RAMONROIs and lims-rois are going to be pretty confusing.  Could we name the lims-roi something else?

**Comment by j6k4m8** [comment]
totally. feel free to pitch ideas here, or of course, PR :)

**Comment by jovo** [comment]
agreed, great functionality, confusing name.
i don't have a better suggestion, but we can't use ROI.

**Comment by wrgr** [comment]
subvolume?  location?

**Comment by jovo** [comment]
all good options.
blob?

On Thu, Feb 25, 2016 at 12:51 PM, William Gray notifications@github.com
wrote:

> subvolume? location?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/neurodata/ndio/issues/118#issuecomment-188902407.

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by j6k4m8** [comment]
I vote against blob because some of our well-known data come from V1 and that seems confounding to me... (Also it's a bad name even in V1, but that's neither here nor there). 

Another vote for `subvolume`! or `region`, `example`?

**Comment by wrgr** [comment]
let's do subvolume.  I don't like region.

**Comment by jovo** [comment]
i don't see what you mean, but i'm outvoted anyway.
subvolume it is.

On Thu, Feb 25, 2016 at 1:35 PM, Jordan Matelsky notifications@github.com
wrote:

> I vote against blob because some of our well-known data come from V1 and
> that seems confounding to me... (Also it's a bad name even in V1, but
> that's neither here nor there).
> 
> Another vote for subvolume! or region, example?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/neurodata/ndio/issues/118#issuecomment-188921611.

## 

the glass is all full:  half water, half air.
neurodata.io
