### ISSUE TITLE
pip install issues using python 3.5

### ISSUE THREAD

**Issue by dkleissa** [openconnectome/ndio#12]
In a clean 3.5 virtualenv, pip install ndio has a few issues:
- Requirements are not installed
- Packing importing fails. Looks like changing **init**.py from:

``` python
from Remote import Remote
from OCP import *
from OCPMeta import *
```

to

``` python
from .Remote import Remote
from .OCP import *
from .OCPMeta import *
```

helps.
- cStringIO is not present in python 3, so this package doesn't appear to be python 3 compatible as the website states.  From Python 3.0 changelog:

> The StringIO and cStringIO modules are gone. Instead, import the io module and use io.StringIO or io.BytesIO for text and data respectively.

**Comment by wrgr** [comment]
We will fix this.  python 2.7 should work in the meantime.
Do you need python 3.x for ndio?

**Comment by dkleissa** [comment]
Ideally python 3, but can use python 2 for now so not a huge problem.

I'd recommend pulling the text saying ndio is a python 3 package at least.

**Comment by dkleissa** [comment]
I just tried pip install again using python 2.7.5 (default OSX install at the moment) in a clean virtualenv.

I then tried to do the "Download an image" demo:

``` python
import ndio.remote.OCP as OCP
import ndio.convert.png as ndpng
from PIL import Image

# Create OCP object
oo = OCP()

token = 'bock11'
channel = 'image'
x_start = 11000
x_stop = 11500
y_start = 11000
y_stop = 11500
z_index = 4000
resolution = 3

# Get image based on token, channel, xstart, xstop, ystart, ystop, z slice index, and resolution index
binary_img_data = oo.get_image(token, channel, x_start, x_stop, y_start, y_stop, z_index=z_index, resolution=resolution)

ndpng.export_png('bock11-demo.png', binary_img_data)

Image.open('bock11-demo.png')
```

I'm getting an error that looks like package importing is still not done properly?  Are you guys using this successfully from pip install?

``` bash
(example_data)XXX:example_data XXXX$ python ./download_slice.py 
Traceback (most recent call last):
  File "./download_slice.py", line 20, in <module>
    binary_img_data = oo.get_image(token, channel, x_start, x_stop, y_start, y_stop, z_index=z_index, resolution=resolution)
AttributeError: 'OCP' object has no attribute 'get_image'
```

**Comment by pmanava1** [comment]
Try  oo.get_xy_slice instead of get_image.

**Comment by wrgr** [comment]
Thanks - guys - where is the get_image example?  It's out of date documentation.  We moved to explicit get_{xy}{xz}{zy}_slice calls to try to parallel RESTful endpoints and clarify.

**Comment by dkleissa** [comment]
The ndio website points you here: https://github.com/openconnectome/ndio-demos/tree/master/Getting%20Started

After switching to get_xy_slice(), ndpng.export_png() fails.  

If you have better up-to-date demos or doc that would be helpful.  http://docs.neurodata.io/ndio/index.html doesn't show the get_xy_slice() method.

**Comment by j6k4m8** [comment]
Sorry about the frame-shift mutation in the docs. My plan is to have all of this worked out sometime this week. I'll update the docs about Python 3 — though 3 support is definitely in the works for the coming few months.

**Comment by j6k4m8** [comment]
There was an error in the code that was causing `get_cutout` to return data of the wrong type. I've resolved and added some clarification in the [Download Functions](https://github.com/openconnectome/ndio-demos/blob/master/Getting%20Started/Downloading%20a%20Volume.ipynb) section of the Getting Started page.

You can update ndio with `pip install -U ndio`. After updating, your version should be `0.0.18`. Please feel free to reach out if you run into any other issues!

**Comment by j6k4m8** [comment]
@dkleissa I spent some time getting ndio to be fully 3.5-compatible. The current version release from pip (0.0.22) supports 2.7 and 3.5. Still need to do a ton of debugging to check for corner-cases, but this is a start :)
