### ISSUE TITLE
Server Naming

### ISSUE THREAD

**Issue by kunallillaney** [openconnectome/ndio#132]
@j6k4m8 @willgray You should consider naming the [DEFAULT_HOSTNAME](https://github.com/neurodata/ndio/blob/master/ndio/remote/neurodata.py#L27) as openconnecto.me/ocp as opposed to just openconnecto.me. This helps in debugging later when we debug with the dev django server.
I believe the only change you might have to do is [here](https://github.com/neurodata/ndio/blob/master/ndio/remote/neurodata.py#L85). What this means is that I can slip in a dev server URL at one point without having to change a whole bunch of stuff. Maybe make this into a environment-type parameter which can set via function(wrap it around a function with a default value). The user can then change the server value once without having to do so for every fucntion.

**Comment by j6k4m8** [comment]
Good call. Figured the `ocp` was more or less set in stone, this is good to know. Confirmed that that's the only location where a change is needed.

**Comment by j6k4m8** [comment]
This is fixed in #143 :)

**Comment by kunallillaney** [comment]
Great thanks.
