### ISSUE TITLE
Better tests for autoingest

### ISSUE THREAD

**Issue by kunallillaney** [openconnectome/ndio#134]
@Aeusman We have to design new tests for autoingest in NDIO. For this we need to check that all the exception handling we do here is correct and catches bugs from the "smart" user. Let's take the discussion offline but the current series of tests you have is not relevant and duplication of effort as they exist in the back-end.
@j6k4m8 @willgray These tests will be self-contained and not break travis.

**Comment by j6k4m8** [comment]
@Aeusman I think we can close this, on latest `master`? :D

**Comment by Aeusman** [comment]
Woops, yeah I'll close.
