### ISSUE TITLE
(More) Error Handling for Users

### ISSUE THREAD

**Issue by Aeusman** [openconnectome/ndio#135]
| ndio version | os | python |
| --- | --- | --- |
| * | * | * |
- [ ] Json-Schema pattern matching (check for special characters and all lowercase)
- [ ] Check folders match channel names
- [ ] Check correct number slices
- [ ] Check image type
- [ ] Check dtype of image
- [ ] Check dimensions of numy array

**Comment by j6k4m8** [comment]
closeable, @Aeusman?

**Comment by Aeusman** [comment]
Closable
