### ISSUE TITLE
validate ID query outputs

### ISSUE THREAD

**Issue by wrgr** [openconnectome/ndio#141]
My CAJAL query on kasthuri_ramon_v3 yields 161k vesicles.  ndio yields 3k vesicles.  
Let's do this afternoon.

**Comment by wrgr** [comment]
ramon.RAMONOrganelle seems to not filter correctly?

**Comment by wrgr** [comment]
this is a horrible bug somewhere...assigning to will - seems to be ??? in CAJAL or something.  Not an ndio error.

**Comment by j6k4m8** [comment]
should i close here and we can reopen in cajal, or leave it for reference?

**Comment by wrgr** [comment]
let's leave open for now.  I'm going to redo the upload.  My suspicion is that having a cell array of objects with 100,000 objects just broke the world.  Doing in smaller batches.  Once we know what happened, we'll move or close.  Assignee here is me.  :)

**Comment by wrgr** [comment]
fixed - cajal packaging can't handle 100k uploads.
