### ISSUE TITLE
map .cutout to .data

### ISSUE THREAD

**Issue by wrgr** [openconnectome/ndio#142]
disregard voxel stuff - just a map/pointer right now.

**Comment by j6k4m8** [comment]
considering getting rid of this entirely, and using `.cutout` to return cutout, or `.voxels` to dynamically rewrite on the fly (and cache). thoughts?

**Comment by wrgr** [comment]
for v1.0 cutout is cutout, voxels are voxels.  voxels are lower priority and fine to punt.

**Comment by wrgr** [comment]
obe - this is post 1.1
