### ISSUE TITLE
Do we support getPropagate and setPropagate?

### ISSUE THREAD

**Issue by kunallillaney** [openconnectome/ndio#144]
Just curious if we support this?

**Comment by j6k4m8** [comment]
not yet — PRs welcome! Otherwise, it's in the pipeline for end-of-month

**Comment by kunallillaney** [comment]
@j6k4m8 I am in no hurry. Whenever you do it, let me know. thanks!

**Comment by kunallillaney** [comment]
@j6k4m8 This seems to be supported. Line 1089 in neurodata.py

**Comment by j6k4m8** [comment]
whoa… apparently i wrote this.

On Mon, Mar 7, 2016 at 7:20 PM Kunal Lillaney notifications@github.com wrote:
@j6k4m8 This seems to be supported. Line 1089 in neurodata.py
