### ISSUE TITLE
should we have a capability to explicitly save/load data

### ISSUE THREAD

**Issue by wrgr** [openconnectome/ndio#152]
thinking in convert

save vol
load vol
save ramon
load ramon

thoughts?  i realize that if we store as npy it's pretty simple, but still a thing.  I often get weird things like .tofile vectorizes my arrays...a standard would be nice.  @j6k4m8

**Comment by j6k4m8** [comment]
for ramon, try

``` python
import ndio.ramon as ramon
# assumed download or create a ramon object "r"

ramon.ramon_to_hdf5(r) # returns a h5py.File object which you can write to disk
```

---

As for volumes, I could write wrappers to numpy's writers and readers to make life easier on us?

**Comment by wrgr** [comment]
Sounds perfect.  We'd also need a hdf5_to_ramon or some such

Possibly better to do:  `save_ramon` `load_ramon` `save_volume` `load_volume` and abstract the details from the user.

**Comment by j6k4m8** [comment]
check out /ramon/**init**.py — save_ramon would ambiguously refer to either
json or hdf5.

I'm thinking about renaming as to_json, from_json, to_hdf5, from_hdf5, so
`ramon.to_hdf5` would replace the above call. Wasn't sure how much existing
code that'd break..?

**Comment by wrgr** [comment]
no existing user facing code.  I think your approach is great.  The alternative of optional arguments denoting type seems worse in this case.
