### ISSUE TITLE
wrap graph-services?

### ISSUE THREAD

**Issue by jovo** [openconnectome/ndio#16]
http://openconnecto.me/graph-services/buildgraph/#programmatic

there are about 6 of them, seems easy enough, 
and it would make ndio the 1 tool that could be used to access any kind of data that neurodata stores.

@j6k4m8 what do you think? disa provided python samples, so it should be easy enough?

**Comment by j6k4m8** [comment]
i'm on it :)

**Comment by j6k4m8** [comment]
[i made dis](https://github.com/openconnectome/ndio/blob/master/ndio/remote/m2g.py)

**Comment by disa-mhembere** [comment]
Don't be sad, but [here](https://github.com/openconnectome/m2g/tree/disa-dev/MR-OCP/MROCPdjango/examples) some other functions that are part of this that would be great if wrapped as well

**Comment by jovo** [comment]
@disa-mhembere i wasn't gonna tell him that until _after_ NYE :+1:

**Comment by j6k4m8** [comment]
Awesome, I knew they existed but couldn't find them. Stand by!

**Comment by disa-mhembere** [comment]
Coolness

**Comment by j6k4m8** [comment]
@disa-mhembere do you have test-files for any of these so I can verify that things are playing nice? the `ndio.remote.m2g` submodule now supports `build_graph`, `compute_invariants`, and `convert_graph`

**Comment by disa-mhembere** [comment]
This is what I use to test:
https://github.com/openconnectome/m2g/tree/disa-dev/MR-OCP/MROCPdjango/examples/tests.
helpful?

**Comment by disa-mhembere** [comment]
There are also test data files: Here:
http://openconnecto.me/mrdata/static/perm/testdata/. You can use those
fibers to post to check see if the buildgraph works and there is a graph
for convert etc ..

**Comment by disa-mhembere** [comment]
i rebooted just now because supervisor stopped running for some reason.
Give me an hour before you test

**Comment by disa-mhembere** [comment]
Never mind it seems all is well :)

**Comment by j6k4m8** [comment]
any thoughts on why I'd be getting empty `""` HTTP-200 responses but no email?

**Comment by disa-mhembere** [comment]
This kind of thing is hard to debug. I usually run it locally to ensure the
request url is actually correct.

But you could try to use the example script to get a response first then
make sure the ndio one matches?

**Comment by j6k4m8** [comment]
Off to a good start. Here's [an update](https://github.com/openconnectome/ndio-demos/blob/master/m2g/Converting%20Graphs%20Between%20Types.ipynb), with more to come.

**Comment by disa-mhembere** [comment]
Awesome!

**Comment by j6k4m8** [comment]
@disa-mhembere let me know a good time for us to go through these endpoints and ensure they're doing what I think they're doing.

**Comment by disa-mhembere** [comment]
Let's do this next week after lunch monday

**Comment by wrgr** [comment]
critical humans are will, disa, jordan, and @gkiar 

@jovo

**Comment by disa-mhembere** [comment]
@j6k4m8 : There is test data on every page for you to use to verify.
