### ISSUE TITLE
single slice uploads

### ISSUE THREAD

**Issue by wrgr** [openconnectome/ndio#160]
support single slice uploads

**Comment by j6k4m8** [comment]
Would you want to be able to upload `yz` slices too?

**Comment by wrgr** [comment]
I would!  Basically seems like converting any 2d array to a 3d array so that it works would help...I'm open to explicit slice (xy, yz, xz) functions, but seems less critical to me.  Thoughts?

**Comment by j6k4m8** [comment]
My vote is that you pass these things as a single slice to post_cutout — adding three slicing functions seems a bit overkill, especially since they'll be an extra location for bug introduction. Thoughts on that?

**Comment by wrgr** [comment]
i agree - but i want ndio to support 2d uploads - currently i think this fails because it expects a 3d array.  So if 2d data, make 3d data, and proceed apace.

Only other thing to ponder is that you have to do slice, slice+1 which is confusing to new users, but I think we can handle that in docs.

**Comment by Aeusman** [comment]
Don't fully remember this discussion, so correct me if I'm wrong, but I believe we decided sometime end of last year that we no longer would support single slice uploads in favor of an autoingest-or s3-ingest instead because of performance issues.
