### ISSUE TITLE
CAJAL tests

### ISSUE THREAD

**Issue by jovo** [openconnectome/ndio#17]
https://github.com/openconnectome/CAJAL/blob/master/test/matlab/api/testOCP.m

not sure we want to replicate those tests, 
hopefully, most of them are now (or will soon be) redundant with neurodata tests.
so this is just a pointer for future reference.

**Comment by alexbaden** [comment]
@j6k4m8 these mostly test restful endpoints. that testing functionality should exist in ocp tests too, but if neurodata incorporated some testing of restful endpoints that would alert everyone should something [inadvertently] change.

**Comment by wrgr** [comment]
Yah - we need a set of tests on the user side to be sure that things are
consistent. In a perfect world they would mirror with nd backend but
something better than nothing.

**Comment by jovo** [comment]
@willgray can you clarify what you mean by the word "need".
to me, ndio tests seem like something we should be rolling out faster than we add functionality, but since we don't currently "need" any new functionality, nor do we have a gameplan, i assumed we would not currently be adding any tests.

**Comment by j6k4m8** [comment]
I'm rolling out tests for ndio as I roll out functionality — some of these tests duplicate CAJALian tests, others are more broad to ensure that Python is behaving as it should. Good to close this in light of the `tests/` directory in this repo?

**Comment by jovo** [comment]
fine with em.

**Comment by wrgr** [comment]
closing.  these will be especially important as we move to the new branch.
