### ISSUE TITLE
deleting read only channels returns True

### ISSUE THREAD

**Issue by wrgr** [openconnectome/ndio#170]
fails as expected in reality, but confusing for user.  

To investigate and either fix or assign to ndstore team

**Comment by j6k4m8** [comment]
I think this is actually an ndstore issue — I only return True because I see a 200 code. @kunallillaney, for discussion sometime next week? low urgency

**Comment by Aeusman** [comment]
Recommending change to returning content of GET after better documentation on how to handle this [here](http://docs.neurodata.io/ndstore/api/json_api.html?highlight=delete)

**Comment by j6k4m8** [comment]
Closed in #231 :)
