### ISSUE TITLE
Version check for ndio should time out with no internet

### ISSUE THREAD

**Issue by wrgr** [openconnectome/ndio#172]
| ndio version | os | python |
| --- | --- | --- |
| 1.0 | macosx | 2.7 |

Currently I can't (easily) use ndio without an internet connection because of the check to pypi for a new version.  I could disable the warning, but seems not intuitive to a new user...

ConnectionError: HTTPSConnectionPool(host='pypi.python.org', port=443): Max retries exceeded with url: /pypi/ndio/json (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x110bced50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))

**Comment by j6k4m8** [comment]
great catch!

**Comment by j6k4m8** [comment]
Resolved by #177!
