### ISSUE TITLE
contribute guidelines?

### ISSUE THREAD

**Issue by jovo** [openconnectome/ndio#18]
we could link to: http://scikit-image.org/docs/stable/contribute.html
or https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt#docstring-standard

or http://scikit-learn.org/stable/developers/contributing.html

thoughts?

**Comment by j6k4m8** [comment]
We may need to make some slight modifications because our docstrings have a different format. But I'm all for having this up and in the repo asap.

**Comment by jovo** [comment]
if numpy, scipy, scikit-learn, and scikit-image all use the same standard, 
it might make more sense to follow that standard, 
because some of the stuff we would probably actually want to port there.
for example, the convert module & ndreg might both belong there?
