### ISSUE TITLE
fix travis cache

### ISSUE THREAD

**Issue by j6k4m8** [openconnectome/ndio#182]
| ndio version | os | python |
| --- | --- | --- |
| * | * | * |

as per #181, travis isn't caching correctly

**Comment by Aeusman** [comment]
@j6k4m8 Travis is failing on install of blosc, separate issue or related? : https://travis-ci.org/neurodata/ndio/jobs/144768396

**Comment by j6k4m8** [comment]
Separate — also, possibly a known issue on new Ubuntus.... Yuck.

**Comment by Aeusman** [comment]
Crud, its messing up all the PRs

**Comment by wrgr** [comment]
i leave you guys alone for like ... 5 minutes!  

lol.  obviously not your fault.  I have trouble with new versions of blosc in general being ahead of stable OSes, especially osx, but maybe ubuntu as well now? 

Try pip install python-blosc==1.3

1.2 probably works if 1.3 doesn't.
