### ISSUE TITLE
microns branch does not like /overwrite/ in RAMON URL

### ISSUE THREAD

**Issue by alexbaden** [openconnectome/ndio#186]
| ndio version | os | python |
| --- | --- | --- |
| 1.0.0 | ocp microns | 2.7 |

Not sure if this is your bad or our bad. We should look later.

**Comment by alexbaden** [comment]
This may actually be my bad... standby.

**Comment by alexbaden** [comment]
```
[14/Apr/2016 16:57:37] ERROR [neurodata:ndwsrest:1169]Get interface overwrite requested. Illegal or not implemented. Args: collman15/annotation/overwrite/
```

**Comment by j6k4m8** [comment]
just following up on this — ndio bug? looks like a sever-side thing but I'm happy to help attenuate on the client-side.
