### ISSUE TITLE
ramon xyz_offset bug

### ISSUE THREAD

**Issue by wrgr** [openconnectome/ndio#190]
| ndio version | os | python |
| --- | --- | --- |
| 1.0 | osx | 2.7 |

As far as I can tell, ndio is always returning:
`'xyz_offset': (0, 0, 0)}`

regardless of actual paint position.  This field is different than regular metadata in that it should be updated from the spatial position depending on the request.  More details as needed.  Here's an example snippet:

```
import ndio.remote.neurodata as neurodata
nd = neurodata()
nd.get_ramon('kasthuri2015_ramon_v4','synapses',3)
s = nd.get_ramon('kasthuri2015_ramon_v4','synapses',3,include_cutout=True)
vars(s)
```

**Comment by Aeusman** [comment]
Unable to replicate, I have a feeling this data was lost in Dsp-pocalypse. Can re-open, but closing for now pending decision what to do with the loss of ramon metadata problem.
