### ISSUE TITLE
print url when url fails?

### ISSUE THREAD

**Issue by alexbaden** [openconnectome/ndio#191]
| ndio version | os | python |
| --- | --- | --- |
| * | * | * |

```
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: NOT FOUND
```

It's tricky to figure out what problem is with the URL when you can't see the URL!

**Comment by alexbaden** [comment]
That error came from the channel being read only. Maybe ndstore should return something different for a readonly channel?

**Comment by j6k4m8** [comment]
my vote would definitely be for a more descriptive ndstore status code since in most cases i just relay whatever i'm given. but i'll definitely look into better readonly behavior overall: tagging #170 for reference.

**Comment by Aeusman** [comment]
[Jin] - Week 1

**Comment by Aeusman** [comment]
@jyshin93

**Comment by Aeusman** [comment]
Pending #266 For get requests, will add post and delete later when re-wiriting those methods.

**Comment by Aeusman** [comment]
Merged
