### ISSUE TITLE
fix convert 

### ISSUE THREAD

**Issue by wrgr** [openconnectome/ndio#192]
| ndio version | os | python |
| --- | --- | --- |
| 1.1 | osx | 2.7 |

Fix transpose issues in convert - seem to be across several different functions as a result of the previous switch to xyz

**Comment by wrgr** [comment]
This is stopping science.  Victory is a script that scrapes kasthuri11 successfully.

**Comment by j6k4m8** [comment]
Interesting... Going to expound on this, and make this issue: (1) find/fix
bug, and (2) figure out why test-suite doesn't catch this

**Comment by wrgr** [comment]
@j6k4m8 - is this fixed now?

**Comment by Aeusman** [comment]
Fix in #230
