### ISSUE TITLE
work on dependency upgrading

### ISSUE THREAD

**Issue by wrgr** [openconnectome/ndio#193]
| ndio version | os | python |
| --- | --- | --- |
| 1.1 | osx | 2.7 |

ndio upgrades (minimum versions) break osx python (or at least mine, using either anaconda or mac python).  h5py==2.5 and blosc==1.2 work great.  We should be careful with these or leave breadcrumbs to new users.  Have been unfun to sort out.  :)

**Comment by j6k4m8** [comment]
would you be willing to PR a change to `setup.py` to that effect?

**Comment by j6k4m8** [comment]
Does the recent blosc update resolve this, @wrgr?

**Comment by wrgr** [comment]
Nope!  Sadly.  1.3.3 was still broken. Don't have debug logs here but can find if you like.

**Comment by Aeusman** [comment]
I believe this was resolved in Blosc 1.5.1
