### ISSUE TITLE
Chessboard Dataset download speed

### ISSUE THREAD

**Issue by aksimhal** [openconnectome/ndio#195]
| ndio version | os | python |
| --- | --- | --- |
| 1.0.0 | OSX | 2.7 |

What should be the download speed for accessing the [chessboard](http://www.nature.com/articles/sdata201446) dataset?  Using ndio, I currently average somewhere between 0.5 to 1 MB/s.  I'm curious if the issue is with Duke's network or if those are the expected speeds. 

Thanks!

**Comment by wrgr** [comment]
assigning to kunal - these issues should go in ndstore repo.  But are fine here at the moment.  :)

**Comment by aksimhal** [comment]
On Wed, May 18, 2016 at 12:10 PM, William Gray notifications@github.com
wrote:

> issues should go in ndstore repo

My apologies - I did not know about the ndstore repository (and its
purpose).

Thanks!
Anish

**Comment by wrgr** [comment]
no worries.  :)  And hi!

@jovo - I don't know if you have a place where you want dataset/infrastructure specific questions.  These are issues relating to missing data resolution perhaps and server latency.

**Comment by jovo** [comment]
@willgray nobody seems motivated to figure out a different system, so i think this is what we got for now.

fwiw, it is _not_ clear whether this is an ndio issue, or an ndstore issue.
to determine the answer, @aksimhal has to run the RESTful call directly himself.

**Comment by kunallillaney** [comment]
The speed is fine here. The call I did was instant. Are cutouts a factor of 128x128x16?

**Comment by jovo** [comment]
i suspect this is a duke/nc thing, having nothing to do with ndio/ndstore.
but anish has to check using the RESTful call.

On Wed, May 18, 2016 at 3:49 PM, Kunal Lillaney notifications@github.com
wrote:

> The speed is fine here. The call I did was instant. Are cutouts a factor
> of 128x128x16?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/neurodata/ndio/issues/195#issuecomment-220137845

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York
