### ISSUE TITLE
Unable to retrieve Chessboard Data Ex13R51

### ISSUE THREAD

**Issue by aksimhal** [openconnectome/ndio#196]
| ndio version | os | python |
| --- | --- | --- |
| 1.0.0 | OSX | 2.7 |

Hello!  

When attempting to access Ex13R51, python returns the following error: 

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Library/Python/2.7/site-packages/ndio/remote/neurodata.py", line 77, in wrapped
>     return f(self, _args, *_kwargs)
>   File "/Library/Python/2.7/site-packages/ndio/remote/neurodata.py", line 522, in get_cutout
>     z_start, z_stop, neariso=neariso)
>   File "/Library/Python/2.7/site-packages/ndio/remote/neurodata.py", line 596, in _get_cutout_blosc_no_chunking
>     req.text))
> IOError: Bad server response for http://openconnecto.me/ocp/ca/Ex13R51/DAPI_1/blosc/0/0,10/0,10/0,10/: 404: (1146, "Table 'Ex13R51.res0' doesn't exist")

The following lines of code run without an error: 

```
import ndio.remote.neurodata as neurodata
nd = neurodata()
token = 'Ex13R51'
channels = nd.get_channels(token)
print channels.keys()
```

Setting up a query: 

```
query = {
    'token': token,
    'channel': 'DAPI_1',
    'x_start': 0,
    'x_stop': 10,
    'y_start': 0,
    'y_stop': 10,
    'z_start': 0,
    'z_stop': 10,
    'resolution': 0
}
```

When I call the query 

```
example_volume = nd.get_cutout(**query)
```

I receive the error I posted above. 

Thanks!

**Comment by wrgr** [comment]
Not an ndio error - related to raw data - reassigning to kunal.  Feel free to redirect.

**Comment by kunallillaney** [comment]
Fixed.
