### ISSUE TITLE
NDIngest cannot be imported

### ISSUE THREAD

**Issue by Aeusman** [openconnectome/ndio#198]
| ndio version | os | python |
| --- | --- | --- |
| 1.1.0 | Ubuntu | 2.7 |

import ndio.remote.ndingest fails with:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named ndingest

Modules at the same level like neurodata (import ndio.remote.neurodata) are fine.

**Comment by Aeusman** [comment]
Turns out Ubuntu 16.04 has some sort of issue with multiple pip variants, and during install the ndio packages were not installing properly. May want to check into this later, but for now was solved by simply removing the existing version, installing each required package manually, and then installing ndio via git clone+pip.

**Comment by j6k4m8** [comment]
This is not Ubuntu's fault, it is a common strategy to deal with having py2
and py3 on the same machine — but it should still import correctly if you
installed ndio correctly! Is this something we need to address further?

**Comment by Aeusman** [comment]
I tried to replicate the problem on a new distribution so make sure it was just my mistake and couldn't so I'd say no.
