### ISSUE TITLE
verify ndio uploading

### ISSUE THREAD

**Issue by wrgr** [openconnectome/ndio#200]
| ndio version | os | python |
| --- | --- | --- |
| 1.1 | osx | 2.7x |

Unit tests needed for uploading data - weird behavior persists.

**Comment by j6k4m8** [comment]
uh oh.

**Comment by wrgr** [comment]
Goal here is verify RAMON upload and non-RAMON upload.

**Comment by wrgr** [comment]
@j6k4m8 - this is highest priority ndio bug i think

**Comment by j6k4m8** [comment]
@wrgr — resolved in #236!
