### ISSUE TITLE
Bad bad leroy bounds

### ISSUE THREAD

**Issue by wrgr** [openconnectome/ndio#203]
| ndio version | os | python |
| --- | --- | --- |
| 1.1 | osx | 2.7 |

Hmmh.  So ndio calls on image projects return different bounds than anno projects.  Same server behavior across machines (bviz1 or dsps).  Don't know root cause (ndstore, ndio), but wanted to get up here to investigate.  Right now I adjust my call depending on channel.  Blah.

weird corner case.  important to fix.  this issue is intermittent.  Wanted to write it down somewhere.

```

import numpy as np
from ndio.remote.neurodata import neurodata
nd = neurodata()
#nd = neurodata(hostname='brainviz1.cs.jhu.edu') #note server
token = 'kasthuri2015_ramon_v4'

pad = [250, 250, 60]
x = 1000
y = 1000
z = 1000

im = nd.get_cutout('kasthuri11cc', 'image', x - pad[0], x + pad[0],y - pad[1], y + pad[1], z - pad[2], z + pad[2], resolution = 1)
anno = nd.get_cutout(token, 'neurons', x - pad[0], x + pad[0],y - pad[1], y + pad[1], z - pad[2], z + pad[2], resolution = 1)

np.shape(im) #[500,500,100]
np.shape(anno) #[498,500,100]

# pad[0] += 1 #TODOTODO

```

**Comment by alexbaden** [comment]
Is it possible https://github.com/neurodata/ndio/issues/229 fixed the problem? I just ran your sample and didn't have an issue.

**Comment by wrgr** [comment]
We think that this is related to:  https://github.com/neurodata/ndstore/issues/303
But not totally sure.

**Comment by Aeusman** [comment]
Closing in favor of the bug report in ndstore.
