### ISSUE TITLE
ndingest returning unexpected error

### ISSUE THREAD

**Issue by gkiar** [openconnectome/ndio#204]
| ndio version | os | python |
| --- | --- | --- |
| 1.1.0 | Mac OSX | 2.7.11 |

I'm trying to upload data to a public project using ndios `ngingest` function, and receiving the error: 

``` python
ValueError: Project and Dataset information Inconistent
```

In my upload script, the dataset information is as follows:

``` python
dataset_name='KKI2009'
project_name='KKI2009v01'
token_name='KKI2009v01'
```

On [openconnecto.me](openconnecto.me), if you log in to the console, you can see that both the `KKI2009` dataset and `KKI2009v01` (in the space of the `KKI2009` dataset) exist, with the same token and information as I gave above.

What is causing this problem?

**Comment by Aeusman** [comment]
investigating

**Comment by Aeusman** [comment]
@gkiar There is an outstanding pull request to fix this problem, but I haven't heard back from Will or Jordan about merging it in. Since it passes tests I'm going to merge it in and I would recommend that you uninstall ndio and re-install it from the github master branch since rolling the version will not happen any time soon.

pip uninstall ndio
git clone https://github.com/neurodata/ndio
cd ndio
python setup.py

**Comment by gkiar** [comment]
Thanks. That enabled me to move forward and get this error:

``` python
OSError: Files are not http accessible:                             Error: 404
```

My data are hosted at [http://openconnecto.me/mrdata/share/ingest/](http://openconnecto.me/mrdata/share/ingest/), and the following command does not return a 404:

``` bash
curl http://openconnecto.me/mrdata/share/ingest/KKI2009v01/113_1/time0/0000.tiff
```

Thoughts on this problem?

**Comment by j6k4m8** [comment]
@Aeusman, please let me know when you need the version rolled. (External and explicit!) The latest PyPI version should now have all of the latest changes (v 1.1.1).

**Comment by gkiar** [comment]
@j6k4m8 I think he's wanting it to work before pushing the fix. Of note: It still doesn't work.

**Comment by Aeusman** [comment]
@j6k4m8 Will do in the future, thanks!

@gkiar Folders should be labeled time0000, time0001, etc. in similar fashion to how the tiffs are labeled, I'm going to update docs to make that more clear. NDingest is working fine because it is identifying that issue

**Comment by j6k4m8** [comment]
Can def see an arg for making the error message spit that out (appending
"did you name them 'blah.tiff'" to the error msg, e.g.).

**Comment by Aeusman** [comment]
Agreed, I'll add that as a separate pull request when ndgraphgen is finished :)

**Comment by gkiar** [comment]
I have updated the times to be in the format you clarified from the [documentation](http://docs.neurodata.io/ndstore/_images/ingesting_directory.png) (my data can again be viewed [here](http://openconnecto.me/mrdata/share/ingest/KKI2009v01/113_1/)), @Aeusman, but am still receiving the same error.

**Comment by Aeusman** [comment]
Would you mind forwarding me the script you are using to ingest? I'll go through and try to identify the issue

**Comment by gkiar** [comment]
Emailing it to you now. Thanks!

**Comment by Aeusman** [comment]
Np! Docs changes are made and pending pull

**Comment by Aeusman** [comment]
@gkiar - Small mistake in naming of data type, should be uint16, not int16. Unclear why this was not caught by the schema, but will check. 

@j6k4m8 This is the edge case I was talking about a few months ago with uint16 tiffs and pillow (used in ndtiff as the load) not being able to read them. I propose detecting this edge case and skipping verify dims as it is unreliable

**Comment by Aeusman** [comment]
@gkiar The work-around for now is to pass verifytype='Folder' as part of the post_data command like so: 

ni.post_data(verifytype='Folder')

What this does is disable checking by image in favor of verifying that the folder structure exists. You will need to (on the web console) delete the existing dataset and projects because you cannot create them with the same name twice, but after that it will run properly

**Comment by gkiar** [comment]
```
From ndio: "SUCCESS. The ingest process has now started."
```

Thanks, micro! I'll let you know if I don't see my data up in a few hours, but for now I think we can consider this closed 👍

**Comment by Aeusman** [comment]
@gkiar Great! For some reason I can't replicate the schema failure bug on my end, so I'll wait and if someone else has this error maybe we can hone in on it.

@j6k4m8 I've moved the edge case problem to a seperate bug #205
