### ISSUE TITLE
NDTiff cannot read int16 tiffs

### ISSUE THREAD

**Issue by Aeusman** [openconnectome/ndio#205]
| ndio version | os | python |
| --- | --- | --- |
| 1.1.1 | Ubuntu | 2.7 |

This is for data stored in Big Endian

**Comment by j6k4m8** [comment]
@Aeusman I think this might be solved by #230 and we can close?

**Comment by Aeusman** [comment]
yep and #192 !

**Comment by j6k4m8** [comment]
WOO
