### ISSUE TITLE
autoingest didn't store my data

### ISSUE THREAD

**Issue by gkiar** [openconnectome/ndio#206]
| ndio version | os | python |
| --- | --- | --- |
| 1.1.1 | Mac OSX | 2.7.11 |

Using the code we debugged in #204, I received the following message in return from ndio:

``` bash
From ndio: "SUCCESS. The ingest process has now started."
```

This was encouraging, until I didn't see my data becoming available on ndstore or through ndviz. @alexbaden was able to query the database for me and found the following:

``` sql
mysql> select count(*) from 113_1_res0;
+----------+
| count(*) |
+----------+
|        0 |
+----------+
1 row in set (0.00 sec)
```

Thoughts on why autoingest didn't actually store my data? @kunallillaney @willgray @j6k4m8 @Aeusman

**Comment by kunallillaney** [comment]
@gkiar Can you post your autoingest code here aka the channel type and datatype as in the script.

**Comment by gkiar** [comment]
``` python
dataset_name='KKI2009'        #(type=str, help='Name of Dataset')
imagesize=(182,218,182)           #(type=int[], help='Image size (X,Y,Z)')
voxelres=(1000000,1000000,1000000)   #(type=float[], help='Voxel scale (X,Y,Z)')
offset=(0,0,0)              #(type=int[], default=[0, 0, 0], help='Image Offset in X,Y,Z')
timerange=(0,33)           #(type=int[], default=[0, 0], help='Time Dimensions')
scalinglevels=0       #(type=int, default=0, help='Required Scaling levels/ Zoom out levels')
scaling=0             #(type=int, default=0, help='Type of Scaling - Isotropic or Normal')
project_name='KKI2009v01'        #(type=str, help='Name of Project. Has to be unique in OCP. User Defined')
token_name='KKI2009v01'          #(type=str, default='', help='Token Name. User Defined')
channel_name='113_1'        #(type=str, help='Name of Channel. Has to be unique in the same project. User Defined.')
datatype='uint16'            #(type=str, help='Channel Datatype')
channel_type='timeseries'        #(type=enum, help='Type of channel - image, annotation, timeseries, probmap')
exceptions=0          #(type=int, default=0, help='Exceptions')
resolution=0          #(type=int, default=0, help='Start Resolution')
windowrange=(0,0)         #(type=int[], default=[0, 0], help='Window clamp function for 16-bit channels with low max value of pixels')
readonly=0            #(type=int, default=0, help='Read-only Channel or Not. You can remotely post to channel if it is not readonly and overwrite data')
data_url= 'http://openconnecto.me/mrdata/share/ingest/'           #(type=str, help='This url points to the root directory of the files. Dropbox is not an acceptable HTTP Server.')
file_format='SLICE'         #(type=str, help='This is overal the file format type. For now we support only Slice stacks and CATMAID tiles.')
file_type='tiff'           #(type=str, help='This is the specific file format type (tiff, tif, png))
public=1              #(type=int, default=0, help='Make your project publicly visible')
metadata=""            #(type=Any, default='', help='Any metadata as appropriate from the LIMS schema')
```

**Comment by kunallillaney** [comment]
@gkiar what library in Python do you use to open your file and load them as numpy arrays? I cannot open them using PIL because this gives me an error(basically I cannot get a numpy array from them). This is what we use to open all our image files and it works for other 16-bit images. We cannot use cv2 because DSP's are scientific linux and they does not play nice with opencv.

**Comment by gkiar** [comment]
I was using libtiff to write them to images, but you're saying I should use PIL instead and see if that works any differently? I'll make an example image and will send it to you to confirm it works on the dsps and then can try reingesting? This will likely happen Wednesday, on my end. Thanks!

**Comment by jovo** [comment]
@willgray knows something secret that he says will solve the problem....

**Comment by kunallillaney** [comment]
@gkiar Sure that works. As long as PIL can read the image.

**Comment by gkiar** [comment]
@willgray want to make your knowledge not secret? You know, in the interest of reproducibility? :)

**Comment by Aeusman** [comment]
@kunallillaney Of note is that all 16-bit tiffs saved in big-endian are not loadable:
http://www.mail-archive.com/image-sig@python.org/msg01131.html 
and no patch for it was released: 
https://bitbucket.org/effbot/pil-117/src/tip/CHANGES?fileviewer=file-view-default

Is scikits an option? It seems like big-endian tiff storage is not an unusual case and we may want to consider explicitly stating in the docs that we cannot accept that type of image.

**Comment by gkiar** [comment]
As it makes no difference to me, I can use pngs that PIL can load as
np.arrays. That happy everyone?

## 

Greg Kiar gkiar07@gmail.com

**Comment by kunallillaney** [comment]
@gkiar For now PIL readable is what we need. We might revisit this at a later stage. Sorry for the trouble. :)

**Comment by wrgr** [comment]
nope - don't know any secret!  

ndio/restful (vs. ndio/ingest) provides functions that will allow for upload of these files, since they are small, with only a couple lines client side.  Because we don't have restful interfaces for create dataset or project, one would do those in the console, and then do:

```
import ndio.remote.neurodata as neurodata

# load data, with nibabel or similar
nd = neurodata()
nd.create_channel(...)
nd.post_cutout(...)
```

This is currently how I upload everything < 100 GB or so.  Is quite fast.

**Comment by Aeusman** [comment]
As far as I can tell _very_ few libraries load big endian 16-bit tiffs properly, maybe cv2 and scikit. Matplotlib, PIL (ndio included), etc. do not load these properly (e.g. converting it to uint8 data or inverting the data) and are well documented as faulty. From looking (admittedly briefly) through Nibabel's source code it looks like tiffs are not supported (https://github.com/nipy/nibabel/blob/master/nibabel/imageclasses.py). 
Loading the images with cv2 or scikit is most definitely not trivial, and there are well documented issues with each (especially for color data), but they are the best option for converting the data.

Of Note: For the superuser like @willgray and @gkiar this is good advice when running into an issue like this, but in general for large uploads users should use the auto-ingest script. Adding another package (especially one that was ruled too large/unwieldy for ndio) over-complicates the average user's process.

**Comment by alexbaden** [comment]
Instead of adding the packages to our end, why not make available a few
scripts that convert tiff to npz, and ingest the npz? We wouldn't even have
to write most of these... @gkiar can write the first one using whatever
library / package works, then we can publish it. It's much easier to add
packages client side or in a client-side VM (ubuntu or virtualbox takes
about 5 mins to setup and works great)!

**Comment by jovo** [comment]
@gkiar - i don't quite understand, can you try @willgray's suggestion and
see if that works, and if not, report back?

On Tue, Jun 14, 2016 at 4:26 PM, Alex Baden notifications@github.com
wrote:

> Instead of adding the packages to our end, why not make available a few
> scripts that convert tiff to npz, and ingest the npz? We wouldn't even have
> to write most of these... @gkiar can write the first one using whatever
> library / package works, then we can publish it. It's much easier to add
> packages client side or in a client-side VM (ubuntu or virtualbox takes
> about 5 mins to setup and works great)!
> 
> On Tue, Jun 14, 2016 at 2:14 PM Alex Eusman notifications@github.com
> wrote:
> 
> > As far as I can tell _very_ few libraries load big endian 16-bit tiffs
> > properly, maybe cv2 and scikit. Matplotlib, PIL (ndio included), etc. do
> > not load these properly (e.g. converting it to uint8 data or inverting
> > the
> > data) and are well documented as faulty. From looking (admittedly
> > briefly)
> > through Nibabel's source code it looks like tiffs are not supported (
> > https://github.com/nipy/nibabel/blob/master/nibabel/imageclasses.py).
> > Loading the images with cv2 or scikit is most definitely not trivial, and
> > there are well documented issues with each (especially for color data),
> > but
> > they are the best option for converting the data.
> > 
> > Of Note: For the superuser like @willgray https://github.com/willgray
> > and @gkiar https://github.com/gkiar this is good advice when running
> > into an issue like this, but in general for large uploads users should
> > use
> > the auto-ingest script. Adding another package (especially one that was
> > ruled too large/unwieldy for ndio) over-complicates the average user's
> > process.
> > 
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > https://github.com/neurodata/ndio/issues/206#issuecomment-225968394,
> > or mute
> > the thread
> > <
> > https://github.com/notifications/unsubscribe/AFkzUmlRHF7vim874YWpaj1kO1Su7Lsqks5qLu96gaJpZM4I0zkF
> > 
> > .
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/neurodata/ndio/issues/206#issuecomment-226005314, or mute
> the thread
> https://github.com/notifications/unsubscribe/AACjcj2gPYHpYqPTe9V1jaT9eV1jUHgxks5qLw5jgaJpZM4I0zkF
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by wrgr** [comment]
these all exist in `ndio.convert` - there's an open bug when we switched axes to xyz from zyx, so complain in that issue if there are issues.

@alexbaden - the reason this is hard is because if you have 1PB of data, it is super annoying to do this conversion.  If you have 10GB of data, there's no reason - just use ndio/restful.

**Comment by wrgr** [comment]
But @gkiar - yea, try this thing I wrote first.  :)

**Comment by alexbaden** [comment]
If you have 1PB of data and a conversion script, you deploy it on a swarm
of docker containers / EC2 instances and go to town. Easy. :-)

**Comment by wrgr** [comment]
sure, but expensive and annoying.  And you the non-CS biologist doesn't know how to do that...

Or you could deploy a lambda service but again, complexity.

**Comment by gkiar** [comment]
Seems this thread got commandeered a bit...

@kunallillaney I have updated my images to be pngs which are int8 and readable by PIL which I have confirmed on bc1. Still, using the script above (but updating format from `tiff` to `png`, and `uint16` to `uint8`, as well as the token and channel), I am getting errors when trying to read my data. For instance, the following cutout returns the following error:
_cutout:_

```
http://openconnecto.me/ocp/ca/KKI2009v03/815_1/xy/0/0,182/0,218/105/
```

_error:_

```
(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1")
```

**Comment by wrgr** [comment]
For initial proof of life, recommend using the code snippet I posted above. 

You can simply read in your data with nibabel, do no conversion and post your numpy data, using dataset/token/channel created using the console.  
- I don't remember if we explicitly deal with 4D data yet, so possible you'll have to slice, but let us know.  It's an easy update - just wasn't a need.  I'm working on case studies, but can answer questions.

**Comment by gkiar** [comment]
That's my current experiment. I wanted to see through trying kunal's suggestions before abandoning autoingest. 👌

**Comment by Aeusman** [comment]
http://openconnecto.me/ocp/ca/KKI2009v03/815_1/xy/0/0,182/0,218/105/15/ 
^  For timeseries need to add the time point at the end

No data at the moment because of re-ingesting to debug a thing

**Comment by Aeusman** [comment]
This has been solved: http://openconnecto.me/ocp/ca/KKI2009v03/815_1/xy/0/0,150/0,150/0/0/

There was an issue in the backend that didn't allow time cubes to be properly inserted

**Comment by wrgr** [comment]
Hey - this is cool!

For reference, this is a prettier slice to show off your hard work:  http://openconnecto.me/ocp/ca/KKI2009v03/815_1/xy/0/0,218/0,182/90/10/

**Comment by jovo** [comment]
that's so wonderful!!!!!

@alexbaden - it kinda works in ndviz too:
http://viz.neurodata.io/KKI2009v03/#

@gkiar - try ingesting another subject?

@aeusman - are the docs up to date for ingesting MRI data?

On Fri, Jun 24, 2016 at 11:16 AM, William Gray notifications@github.com
wrote:

> Hey - this is cool!
> 
> For reference, this is a prettier slice to show off your hard work:
> http://openconnecto.me/ocp/ca/KKI2009v03/815_1/xy/0/0,218/0,182/90/10/
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/neurodata/ndio/issues/206#issuecomment-228373781, or mute
> the thread
> https://github.com/notifications/unsubscribe/AACjcrOF0N7afSFHu8lqc8F0AtJr7XY3ks5qO_S3gaJpZM4I0zkF
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by wrgr** [comment]
Do this:  http://viz.neurodata.io/KKI2009v03/815_1/0/90/90/90/

Then manually input time 0.  Then hit the play button.  @alexbaden - you can't directly link to a time step, true?  (Tricky thing with DTI is to know where to look for the good stuff.  :) )

**Comment by Aeusman** [comment]
@jovo theres no MRI specific doc for ingesting (because its the same procedure), but I can add a FAQ like "I have MRI data how do I ingest it an visualize it?"

@willgray thanks, that looks a lot nicer! :+1:

**Comment by Aeusman** [comment]
@gkiar The data was ingested in dataset MNI2 instead of MNI because MNI was already taken (Also x=width for imagesize)
