### ISSUE TITLE
python wrappers for console functions

### ISSUE THREAD

**Issue by jovo** [openconnectome/ndio#207]
there are 3 functions in the console that i'd like to have in ndio:
1. create project
2. create token
3. create channel.

getting to use only 1 tool, that wraps _all_ RESTful calls from ndstore, is better than having one that wraps only a subset, imho.

**Comment by wrgr** [comment]
create channel exists.  

create token and project are high priority for me too.  About 4 hours or less to wrap and test once they exist.  We'd also need dataset.

@kunallillaney has security concerns.  I have some ideas about mitigating those (e.g., restful calls get submitted as a temporary user, and projects need to be administratively transferred to named user if >XXGB, or actually doing authentication, or just exposing and not fixing until there is actually a problem (unlikely imho), but need a top down call from @jovo or @randalburns 

Once we had those, ndingest and ndio could be refactored a bit to be one cohesive happy package.  :)
@j6k4m8

**Comment by wrgr** [comment]
To be more explicit, these restful endpoints intentionally have not been exposed.  Once/if they are, we can include in ndio within the same working week or less.

**Comment by jovo** [comment]
@jovo approves and understands the risks.  thanks.

On Wed, Jun 15, 2016 at 9:03 AM, William Gray notifications@github.com
wrote:

> To be more explicit, these restful endpoints intentionally have not been
> exposed. Once/if they are, we can include in ndio within the same working
> week or less.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/neurodata/ndio/issues/207#issuecomment-226180325, or mute
> the thread
> https://github.com/notifications/unsubscribe/AACjcrqPa-NYb50A82XktBZ39yM7zl1zks5qL_gfgaJpZM4I2U--
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by wrgr** [comment]
@kunallillaney - once the ndstore team exposes these endpoints (dataset, project, token), we {will, jordan, ualex} will implement immediately.  Probably can do even without full doc.  Very exciting for me and for science!

**Comment by j6k4m8** [comment]
I'm super pumped for this too — ndio will support this, at most 1 week
after the endpoint is exposed :)

#science!

**Comment by jovo** [comment]
hey are exposed, ndingest uses them.

On Wed, Jun 15, 2016 at 10:12 AM, Jordan Matelsky notifications@github.com
wrote:

> I'm super pumped for this too — ndio will support this, at most 1 week
> after the endpoint is exposed :)
> 
> #science!
> 
> On Wed, Jun 15, 2016 at 10:09 AM William Gray notifications@github.com
> wrote:
> 
> > @kunallillaney https://github.com/kunallillaney - once you expose
> > these
> > endpoints (dataset, project, token), we will implement immediately.
> > Probably can do even without full doc. Very exciting for me and for
> > science!
> > 
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > https://github.com/neurodata/ndio/issues/207#issuecomment-226198637,
> > or mute
> > the thread
> > <
> > https://github.com/notifications/unsubscribe/AAqVB5ccwYy0nIj-ty5CL2FB_B5a9_H9ks5qMAe3gaJpZM4I2U--
> > 
> > .
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/neurodata/ndio/issues/207#issuecomment-226199425, or mute
> the thread
> https://github.com/notifications/unsubscribe/AACjcmVY4o6nCIVXbjuX-K8eIGYRe68Sks5qMAhTgaJpZM4I2U--
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by kunallillaney** [comment]
@jovo There are quite a bit of misconceptions involving what is being discussing here
1. create token and project are NOT exposed via any REStful interface and I will need to write the interfaces for that to be true. This is currently not on my list and I will only get to it in about 2-3 weeks if we decide to ever implement it.
2. autoingest is a totally different work-flow path and has nothing to do with what @willgray has requested and these are 2 separate issues in my mind. We have discussed these before and I still don't understand why @willgray is trying to tie them together. 
3. The idea proposed by @willgray does not work and is broken. Larger picture is that there are grave security concerns here i.e. somebody can DOS us by creating infinite number of databases and so on.  There are other organizational concerns here about user management and data management which need to be thought over.
4. @jovo I will need @randalburns approval for this. He and I have discussed this in the past and we both think that this should not be implemented, this is why we wrote the admin console.

**Comment by Aeusman** [comment]
To add some clarity: ndingest is essentially a glorified way of posting jsons with information about data to the backend, where the backend does the actual heavy lifting. Ndingest doesnt do the job of creating tokens, projects, channels, etc., all of that is handled by the backend.
