### ISSUE TITLE
bugs ndingest.py

### ISSUE THREAD

**Issue by adwanner** [openconnectome/ndio#208]
| ndio version | os | python |
| --- | --- | --- |
| 1.1.1 | ubuntu 14.04 | python 2.7 |

I installed ndio using "pip install ndio" in order to run autoingest.py.
I ran into several errors:
- Line 394 requires to change the variable name "response" to "resp":
  shutil.copyfileobj(resp.raw, out_file)
- I try to upload a stack of z-slices with an offset in Z. The accessibility verification procedures checks if the scaling variable was set and depending on the outcome chooses an offset value that is used to check if the corresponding slice exists. (Lines  339 - 365). 
  The offset value is set in the "verify_path" function, lines 316 - 331. If I understand correctly, line 319 should be offset = data["dataset"]["offset"][2] and probably line 324 and line 329 should be changed as well?  
- It is not clear to me what the "scaling" parameters is used for. In particular, I do not understand what "isotropic orientation (in which each tiff is a slice on the y plane)" means. The term isotropic usually refers to "isotropic resolution" but I do not understand it in this context.

**Comment by Aeusman** [comment]
Hi!

Thanks for the concise report, I'll issue a fix for all.

**Comment by Aeusman** [comment]
PR created

**Comment by kunallillaney** [comment]
@Aeusman Close issue when PR is pulled in. Thanks.

**Comment by Aeusman** [comment]
Fixed in latest pull
