### ISSUE TITLE
why is 'convert' not in pillow?

### ISSUE THREAD

**Issue by jovo** [openconnectome/ndio#21]
to be discussed in person:
it seems like pillow is the natural place for this, because it already has read & write functions for most of the image formats of interest, and it is generally useful code?

of note, pillow is a "highly active" repo: https://www.openhub.net/p/PythonPillow
so i think it makes sense to add to it, rather than put convert in ndio?

@j6k4m8

**Comment by j6k4m8** [comment]
I was planning on `ndio.convert` including things like conversions from
RAMON to other open neuro formats (i.e. neurodata-specific conversions).
Makes sense to have the same syntax for 2d conversion as 3d / 3d+metadata,
right?

**Comment by jovo** [comment]
perhaps.  in that case, i'd write the RAMON conversions to mimic the pillow ones...

**Comment by j6k4m8** [comment]
will do!

**Comment by jovo** [comment]
let's discuss when you are back.
in the meantime, we have tables to make!

On Mon, Jan 4, 2016 at 12:52 PM, Jordan Matelsky notifications@github.com
wrote:

> will do!
> 
> On Sun, Jan 3, 2016 at 7:14 PM joshua vogelstein <notifications@github.com
> 
> > wrote:
> > 
> > perhaps. in that case, i'd write the RAMON conversions to mimic the
> > pillow
> > ones...
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/openconnectome/ndio/issues/21#issuecomment-168557168
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/ndio/issues/21#issuecomment-168750723.

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by j6k4m8** [comment]
short answer is that our `convert` suite is more complete than PIL's (we use PIL for _some_ formats, but not all) and we also convert to and from non-image formats (hdf5, npz, etc). 

Sufficient explanation to close, @jovo?

**Comment by jovo** [comment]
i think i'd rather have a PIL dependency and call PIL functions that exist
than re-implement them (becuase sometimes our implementations are buggy).

do you disagree?

On Mon, Feb 22, 2016 at 8:30 AM, Jordan Matelsky notifications@github.com
wrote:

> short answer is that our convert suite is more complete than PIL's (we
> use PIL for _some_ formats, but not all) and we also convert to and from
> non-image formats (hdf5, npz, etc).
> 
> Sufficient explanation to close, @jovo https://github.com/jovo?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/neurodata/ndio/issues/21#issuecomment-187173256.

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by j6k4m8** [comment]
We do, whenever possible. (The ndio wrappers just ensure that things are
uniform syntax-wise, no matter what underlying library we're using)

**Comment by wrgr** [comment]
+1 to j6k4m8.

I support closing.

**Comment by jovo** [comment]
ok, close.

On Mon, Feb 22, 2016 at 10:32 AM, William Gray notifications@github.com
wrote:

> +1 to j6k4m8.
> 
> I support closing.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/neurodata/ndio/issues/21#issuecomment-187230793.

## 

the glass is all full:  half water, half air.
neurodata.io
