### ISSUE TITLE
import tifffile fails 

### ISSUE THREAD

**Issue by alexbaden** [openconnectome/ndio#232]
```
/home/alex/.virtualenvs/ndstore/local/lib/python2.7/site-packages/ndio/convert/tiff.py in <module>()
      3 import os
      4 import glob
----> 5 import tifffile as tiff
      6 
      7 

ImportError: No module named tifffile
```

Looks like `tifffile` needs to be added to the package list installed via pip.

**Comment by Aeusman** [comment]
from setup.py:

```
install_requires=[
    "pillow>=3.2.0",
    "numpy>=1.0.0",
    "h5py>=2.6.0",
    "requests",
    "blosc==1.3.2",
    "jsonschema",
    "json-spec",
    "tifffile"
]
```

From requirements:
pillow
numpy
h5py
requests
pymcubes
pycollada
blosc==1.3.2
jsonschema
json-spec
tifffile

**Comment by Aeusman** [comment]
Wrong button -.- Can be solved by using latest master branch.

**Comment by alexbaden** [comment]
Ah, I see. Must have had some weird conflict with my copy of master and the download from pypi. Thanks!
