### ISSUE TITLE
get_ramon_ids returning duplicates

### ISSUE THREAD

**Issue by alexbaden** [openconnectome/ndio#238]
```
ids = nd.get_ramon_ids(token='MyToken', channel='annotation')

[1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 10, 10, 10, 10, 10, 10, 10, 10, 12, 12, 12, 12, 12, 12, 12, 12, 15, ...
```

This data isn't public, but I can provide a token / channel via other means. Not sure if this is an ndio or ndstore problem, yet. Documenting and seeing if @j6k4m8 or @wrgr had experienced something similar?

**Comment by wrgr** [comment]
I haven't seen this.  That is indeed the code I usually run...happy to chat if you like via slack or elsewhere.

**Comment by j6k4m8** [comment]
This is intended to be running a `np.uniq` before returning — please PM
details and I'll check it out.

**Comment by j6k4m8** [comment]
Are you still getting this error?
