### ISSUE TITLE
Calling Remote Super Class in Neurodata (Prep for Microns Branch)

### ISSUE THREAD

**Issue by Aeusman** [openconnectome/ndio#240]
In neurodata the ping function returns a 
`super(neurodata, self).ping(suffix)`
What is the reason for the super class reference instead of calling a local ping? Essentially the purpose of this question is that in the new microns branch there will be security authorization for all calls and so each requests.get, post, and delete need to be authenticated, including the ping. Right now the current pull has a getURL method which handles all the underlying auth, so the proposal would be to make that ping a call to the local method instead of the super class.

**Comment by Aeusman** [comment]
@j6k4m8 @wrgr

**Comment by j6k4m8** [comment]
No rationale behind this except that it was a good placeholder in preparation for exactly this scenario. Feel free to change it as it suits you, provided it doesn't break anything :)
