### ISSUE TITLE
merge docker pull request

### ISSUE THREAD

**Issue by gkiar** [openconnectome/ndio#247]
though it "didn't pass tests," that's because master doesn't, and all that was added was a dockerfile :)

**Comment by wrgr** [comment]
see here:  https://travis-ci.org/neurodata/ndio/builds

Seems like it was working before the push?

**Comment by gkiar** [comment]
odd, as it was identical code to alex's update (i added the same dockerfile not realizing he had). Closed mine, suggest you merge his

**Comment by Aeusman** [comment]
This was merged #244
