### ISSUE TITLE
Requirements.txt Failure

### ISSUE THREAD

**Issue by Aeusman** [openconnectome/ndio#25]
@j6k4m8 requirements.txt says urllib2, which is part of python standard lib (to my knowledge), thus failure on pip install -r with: 

Real name of requirement urllib2 is urllib3
Could not find any downloads that satisfy the requirement urllib2 (from -r requirements.txt (line 1))\

Did you mean urllib3?

**Comment by j6k4m8** [comment]
oh wow, that was a good catch. i think we can just kill that requirement, my mistake

**Comment by j6k4m8** [comment]
it is did :)
