### ISSUE TITLE
Add project manangement services to ndio for neurodata

### ISSUE THREAD

**Issue by kunallillaney** [openconnectome/ndio#250]
| ndio version |  os  | python |
|-----|------|-------|
| *   | *    | *     |

**Comment by kunallillaney** [comment]
these services are called resource services and allow create, update, delete on all project meta-data parameters(dataset, project, channel and token)

**Comment by Aeusman** [comment]
[Rahul] - Week 2

**Comment by Aeusman** [comment]
@Cyrob

**Comment by Aeusman** [comment]
Pulled in
