### ISSUE TITLE
Add https support for neruodata

### ISSUE THREAD

**Issue by kunallillaney** [openconnectome/ndio#251]
| ndio version |  os  | python |
|-----|------|-------|
| *   | *    | *     |

**Comment by kunallillaney** [comment]
ndstore now requires HTTPS for non-public tokens. All public tokens will continue to be supported without authentication. The authentication system now requires a user to download a one time token which has included in the HTTPS requests.

**Comment by Aeusman** [comment]
[Jin] - Week 1

**Comment by Aeusman** [comment]
@jyshin93

**Comment by Aeusman** [comment]
[ ] - Set up Vm with ndstore
[ ] - Update user_token in init.
[ ] - Update geturl with error handling for access forbidden
[ ] - Write tests (Blocked until #250 )

**Comment by Aeusman** [comment]
Pulled in
