### ISSUE TITLE
AWS S3 support?

### ISSUE THREAD

**Issue by xiuliren** [openconnectome/ndio#252]
Thanks for making this tool. I have a few questions.

- does ndio support S3 storage, what is the format stored in S3? 
- is there a maximum concurrent IO process? such as 1000 IO requests and each requests 1 GB data?

**Comment by kunallillaney** [comment]
@jingpengwu Sorry for the late reply.
* ndio is the wrapper around ndstore and so supports whatever is supported in ndstore
* ndstore has S3 support and the format stored in S3 is blosc (same as the BOSS). But this service mode for ndstore is currently in beta and has not been made Public
* There is not maximum concurrent process limit for S3 (when it will be deployed). Here I would like to ask you, what are you trying to do? And when you mean 1GB of data is that compresses/uncompressed?

**Comment by xiuliren** [comment]
I am doing MICrON project, as you know, we'll have a lot of workers doing concurrent IO. 1 GB is uncompressed size.

**Comment by kunallillaney** [comment]
@jingpengwu 

* Yes I understand that you are on the MICrON project but my question was more on the workload. Would you be iterating the dataset (i.e moving along a particular axis, not reading the region more then once) or reading the same region multiple times)
* 1GB is fine. Currently our deployment (openconnecto.me) is not deployed on S3 and we only recommend you use 4 readers.
* Once when our S3 deployment goes live you can use 1000 readers but that would be direct S3 access not via our Web-servers.

**Comment by xiuliren** [comment]
Thanks, let's move discussion to slack and close this issue.

Currently, I am iterating the dataset along the axis with a order of x,y,z. I have got the answer of S3 from Dean. We need to fetch a url and then access the chunks directly.
