### ISSUE TITLE
Initialization of Neurodata Fails

### ISSUE THREAD

**Issue by Aeusman** [openconnectome/ndio#258]
sinverso commented 2 hours ago
Hi,
When trying the ipython notebook claims I get an error atnd = neurodata()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() takes at least 2 arguments (1 given)
I've tried python 2.7.11 and 2.7.6.

Thank you,
-Sam

**Comment by Aeusman** [comment]
This is not actually a bug, there is now an additional field that is required for initialization of the object, a user_token. This is the token that is uniquely identifies a user when interacting with the neurodata backend.

**Comment by sinverso** [comment]
Ok, you can close this issue then.
