### ISSUE TITLE
get_cutout and post_cutout broken for image data

### ISSUE THREAD

**Issue by kkutten1** [openconnectome/ndio#273]
| ndio version |  os  | python |
|-----|------|-------|
| 1.1.6  | Ubuntu 14.04    | 2.7.6    |

@Aeusman, @perlman, @kunallillaney 

According to @randalburns newer version of ndstore treat all images as time series.  But this breaks compatibility with the ndio.remote.neurodata.get_cutout and the ndio.remote.neurodata.post_cutout methods.  For example the following...
```
import ndio.remote.neurodata as neurodata
nd = neurodata(hostname="dev.neurodata.io", user_token="myUserToken")
nd.get_cutout("myToken","grayscale",0,100,0,100,0,100,resolution=0)
```
...results in the following error...
```
nd.get_cutout("myToken","grayscale",0,100,0,100,0,100,resolution=0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/.local/lib/python2.7/site-packages/ndio/remote/neurodata.py", line 99, in wrapped
    return f(self, *args, **kwargs)
  File "~/.local/lib/python2.7/site-packages/ndio/remote/neurodata.py", line 554, in get_cutout
    z_start, z_stop, neariso=neariso)
  File "~/.local/lib/python2.7/site-packages/ndio/remote/neurodata.py", line 634, in _get_cutout_blosc_no_chunking
    req.text))
IOError: Bad server response for https://dev.neurodata.io/nd/sd/myToken/grayscale/blosc/0/0,100/0,100/0,100/: 404: '"Failed to retrieve data cubes: 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \')\' at line 1. sql=SELECT zindex,timestamp,cube FROM grayscale_res0 WHERE zindex=0 and timestamp in ()"'

```
...because it generates a url without time parameters...
```
https://dev.neurodata.io/nd/sd/myToken/grayscale/blosc/0/0,100/0,100/0,100/
```
...instead of...
```
https://dev.neurodata.io/nd/sd/myToken/grayscale/blosc/0/0,100/0,100/0,100/0,1/
```

**Comment by kunallillaney** [comment]
@kkutten1 This is true for the future. In the branch currently running on dev.neurodata.io, there are still image and timeseries channels. We will only roll out this feature when ndio actually supports it.

**Comment by kkutten1** [comment]
@kunallillaney: OK. So right now when I add a channel on as an image it creates a time series.  Can this behavior be changed?

Steps to reproduce...
- Log into dev.neurodata.io admin console
- "Projects"->"View Projects"
- For project "myToken", click "channels" which will take you to the "CHANNELS" list page
- Click "Add Channel", enter name "test_channel" for "Channel Name" and select "Images (16-bit)" for "Channel Type"
- Click "Create Channel" and this will take you back to the  "CHANNELS" list page
- On the "CHANNELS" page "Channel Type" for "test_channel" will incorrectly say "time series" instead of "image"

**Comment by kunallillaney** [comment]
@kkutten1 So you are trying to upload image data or annotation data?

**Comment by kkutten1** [comment]
@kunallillaney: Image data.

**Comment by kkutten1** [comment]
@kunallillaney:  I was able to create an "image" channel by using the ndio.remote.neurodata.create_channel method instead of the admin console.

**Comment by kunallillaney** [comment]
@kkutten1 Great. This was a user interface issue which has been fixed now. You can create 8/16/32/64 bit image data via the user interface or ndio. Please choose the project store as MySQL since you cannot post to any other engine for now.  Also, close this issue when you can post data. :)

**Comment by kkutten1** [comment]
@kunallillaney: Thanks.  I can now create "image" type channels through the admin console.
