### ISSUE TITLE
Add user token to request headers of post_cutout and get_cutout

### ISSUE THREAD

**Issue by kkutten1** [openconnectome/ndio#278]
| ndio version |  os  | python |
|-----|------|-------|
| 1.1.6  | Ubuntu 14.04    | 2.7.6    |

Something @kunallillaney @Aeusman and @kkutten1 discussed today.  Workaround is to make project public so fix is not urgently needed.

**Comment by kunallillaney** [comment]
@kkutten1 This is in the pipeline and is #251 which is being worked on currently by one of the undergrads.

**Comment by Aeusman** [comment]
Fixed
