### ISSUE TITLE
neurodata.py refactor getUrl

### ISSUE THREAD

**Issue by adwanner** [openconnectome/ndio#288]
| ndio version |  os  | python |
|1.6.1|ubuntu 14.04 LTS|python 2.7|
| *   | *    | *     |

All calls to getURL(...) in neurodata.py should be replaced by self.getURL(...)

**Comment by Aeusman** [comment]
The pip version is currently out of sync, I recommend using the latest master code from github which can be installed using the setup file in the repository. This change has already been completed.
