### ISSUE TITLE
RAMON Conversion

### ISSUE THREAD

**Issue by j6k4m8** [openconnectome/ndio#3]
- [x] hdf5
- [ ] json
- [ ] npz

@alexbaden tagged because ndv can import ndio
@willgray tagged because is this useful?

**Comment by wrgr** [comment]
definitely useful.

Best,
Will

**Comment by alexbaden** [comment]
Of note, I decided not to accept or output JSON voxel data w/ Ramon objects
on the OCP side.

If you want to upload metadata only, use JSON.
If you want to upload voxel data and metadata, use HDF5.

We can revisit this decision as necessary.
