### ISSUE TITLE
add ability to merge two ids

### ISSUE THREAD

**Issue by wrgr** [openconnectome/ndio#37]
RESTful endpoint here:

http://docs.neurodata.io/open-connectome/api/ramon_api.html?highlight=merge#merge-service

@j6k4m8 - we should talk about this - although nd doesn't do it, we probably want to add a delete object for the ids we get rid of - causes all kinds of trouble when we don't.

**Comment by j6k4m8** [comment]
fixed in https://github.com/openconnectome/ndio/commit/e7de200d57019c10ca5fc5b758a7d8d5cc5c5f50, just the merge, no deletions yet. leaving this open

**Comment by wrgr** [comment]
totally great.  delete should probably be a flag, set to false by default.

**Comment by j6k4m8** [comment]
can we delete via endpoint..?

**Comment by wrgr** [comment]
meaning what is the endpoint?  Or is that ok behavior?

**Comment by j6k4m8** [comment]
perhaps both... but more urgently the first

**Comment by j6k4m8** [comment]
fixed in latest master!
