### ISSUE TITLE
add delete annotation call

### ISSUE THREAD

**Issue by wrgr** [openconnectome/ndio#39]
Add call for delete annotation.

@alexbaden @kunallillaney @Aeusman - do you know what the RESTful endpoint is?  We couldn't find in the documentation.  Also need updateAnnotation.

Thanks!

**Comment by wrgr** [comment]
Here's an example!!
Thanks @kunallillaney 

https://github.com/openconnectome/open-connectome/blob/a26a29f97fb749f033813c7b596356c16c7c5326/examples/annodel.py

**Comment by j6k4m8** [comment]
added in [0.1.6](https://github.com/neurodata/ndio/releases/tag/0.1.6)

**Comment by wrgr** [comment]
Awesome.
