### ISSUE TITLE
implement crop

### ISSUE THREAD

**Issue by wrgr** [openconnectome/ndio#4]
Crop is important because people naively assume what they input is what they get.  

We could either have crop simply wrap the raw restful call explicitly, or keep the padding as is done now and crop it back.  The former seems better and less error prone?

**Comment by j6k4m8** [comment]
raw RESTful call returns cube-aligned data, no?

**Comment by wrgr** [comment]
Nope - returns exact coordinates. I like the plan, but we should
rearchitect a bit. Talk today?

**Comment by j6k4m8** [comment]
Interesting. I wonder if I'm already (almost) doing this correctly. Slack'd
you.

**Comment by wrgr** [comment]
@j6k4m8  - reloading on this - cropping is required to get reference datasets.  Also, if someone says I want this region, we should align internally, but perhaps ultimately give them what they want.  Should I jump in on this?

**Comment by wrgr** [comment]
true that this is closed?  @j6k4m8

**Comment by j6k4m8** [comment]
Yep!!
