### ISSUE TITLE
Add Required Packages to Ndio Install

### ISSUE THREAD

**Issue by Aeusman** [openconnectome/ndio#49]
So this seems like something we should add, I can add in the next pull request I make if you're busy @j6k4m8, thoughts?

**Comment by j6k4m8** [comment]
what do you mean by this?

**Comment by Aeusman** [comment]
Right now when installing ndio it does not install dependencies, felt like this might be a good enhancement to add, but wasn't sure if you were planning to add this or had thought about it already decided not to do it.

**Comment by j6k4m8** [comment]
i think greg may be working on this..? possibly?

**Comment by Aeusman** [comment]
Yep, this was before he started doing that, I'll close
