### ISSUE TITLE
location of data is transparent to the user

### ISSUE THREAD

**Issue by jovo** [openconnectome/ndio#5]
this is arguably the most important function for lowering the barrier to entry.
i also have no idea how hard it is to implement, and whether it exists already :)

essentially, once somebody loads a token/channel into python as an object.
all functions (eg, those in scikit-image, scikit-learn, etc.) should just "work", 
by which i mean if the subcube of the data that they are trying to operate on is small enough to work, then if its already loaded into ram, it should go, and if its not, it should load and go.

on the other hand, if the subcube they try to operate on is too big to fit into ram, or too big for the computation to work, it should say so.

@j6k4m8 @willgray @alexbaden discuss?

**Comment by wrgr** [comment]
I don't understand what you mean exactly, but I think this is indeed what
we do.  :)

Analysis workflows are always:

Get data > do something > put data

Get data takes in tokens, channels, etc., and outputs a cube.  From there,
they'll do vision just like anyone would, whether they started with a tiff
stack or neurodata dataset.

When they are done, they'll upload, following examples, tutorials, and
wrapper functions that we make to ease the process.

If they do something non-compliant with their analysis tool, it will break
- the exception will be returned by scikit image, or open cv - agnostic to
  the way the data was acquired.

Make sense?

Best,
Will

On Sat, Oct 31, 2015 at 6:54 PM, joshua vogelstein <notifications@github.com

**Comment by wrgr** [comment]
As a followup, we've tried to make this super clear, but there will be
explicit tutorials for how to get data into a neutral format (tif stack and
matrix) for ndio, restful calls, and cajal well before the hackathon.

Best,
Will

**Comment by jovo** [comment]
i'm saying:

do something -> put data

ie, doing something gets data as appropriate.
so, i have a 1 TB image.
i type

load('image')

which doesn't actually load the whole thing in RAM, but does something.

then i type

filter('image(idx)')

where idx is a list of voxels to apply 'filter' to.
if those voxels are already in RAM, then the normal thing happens.
if they are not, they are automatically downloaded, and then the normal
thing happens.

maybe better to chat in person...

On Sat, Oct 31, 2015 at 7:00 PM, William Gray notifications@github.com
wrote:

> As a followup, we've tried to make this super clear, but there will be
> explicit tutorials for how to get data into a neutral format (tif stack and
> matrix) for ndio, restful calls, and cajal well before the hackathon.
> 
> Best,
> Will
> 
> On Sat, Oct 31, 2015 at 6:57 PM, William R. Gray Roncal <
> willgray@gmail.com>
> wrote:
> 
> > I don't understand what you mean exactly, but I think this is indeed what
> > we do. :)
> > 
> > Analysis workflows are always:
> > 
> > Get data > do something > put data
> > 
> > Get data takes in tokens, channels, etc., and outputs a cube. From there,
> > they'll do vision just like anyone would, whether they started with a
> > tiff
> > stack or neurodata dataset.
> > 
> > When they are done, they'll upload, following examples, tutorials, and
> > wrapper functions that we make to ease the process.
> > 
> > If they do something non-compliant with their analysis tool, it will
> > break
> > - the exception will be returned by scikit image, or open cv - agnostic
> >   to
> >   the way the data was acquired.
> > 
> > Make sense?
> > 
> > Best,
> > Will
> > 
> > On Sat, Oct 31, 2015 at 6:54 PM, joshua vogelstein <
> > notifications@github.com> wrote:
> > 
> > > this is arguably the most important function for lowering the barrier to
> > > entry.
> > > i also have no idea how hard it is to implement, and whether it exists
> > > already :)
> > > 
> > > essentially, once somebody loads a token/channel into python as an
> > > object.
> > > all functions (eg, those in scikit-image, scikit-learn, etc.) should
> > > just
> > > "work",
> > > by which i mean if the subcube of the data that they are trying to
> > > operate on is small enough to work, then if its already loaded into
> > > ram, it
> > > should go, and if its not, it should load and go.
> > > 
> > > on the other hand, if the subcube they try to operate on is too big to
> > > fit into ram, or too big for the computation to work, it should say so.
> > > 
> > > @j6k4m8 https://github.com/j6k4m8 @willgray
> > > https://github.com/willgray @alexbaden https://github.com/alexbaden
> > > discuss?
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/openconnectome/ndio/issues/5.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/ndio/issues/5#issuecomment-152779635.

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by j6k4m8** [comment]
Ah — I understand better what you're saying now. There are issues with
returning an incomplete volume with our current setup, because doing
something like

```python
data = ocp.get_cutout( . . . )
connected_components(data)
```

is ambiguous: does it mean run CC on the whole volume, or just what's
downloaded — with an extra-weird complication that if it's the former,
which makes a lot more sense, this happens:

```python
>>> data = ocp.get_cutout( . . . ) # runs in a few milliseconds
>>> data.shape                     # runs in a few milliseconds
(100000, 100000, 1000)
>>> connected_components(data) # takes four weeks?!
[ . . . ]
>>> connected_components(data) # takes five seconds?!!!?
```

While this lazy-load queueing is really convenient in cases where it works,
it *really* screws with a user's understanding of how commands can be used.
And because it's complex to implement, my vote is to punt on this until we
have a really good reason.

That being said, it'd be smart of us [me] to document that if you want to
download `image` but only play with `image[idx]`, you should just download
`idx` until you need the rest. Onus is on the python-writer to not download
TB of data indiscriminately, because ndio *is* the tool you'd use to
download TB of data intentionally.

**Comment by j6k4m8** [comment]
Ah — I understand better what you're saying now. There are issues with
returning an incomplete volume with our current setup, because doing
something like

``` python
data = ocp.get_cutout( . . . )
connected_components(data)
```

is ambiguous: does it mean run CC on the whole volume, or just what's
downloaded — with an extra-weird complication that if it's the former,
which makes a lot more sense, this happens:

``` python
>>> data = ocp.get_cutout( . . . ) # runs in a few milliseconds
>>> data.shape                     # runs in a few milliseconds
(100000, 100000, 1000)
>>> connected_components(data)     # takes four weeks?!
[ . . . ]
>>> connected_components(data)     # takes five seconds?!!!?
```

While this lazy-load queueing is really convenient in cases where it works,
it _really_ screws with a user's understanding of how commands can be used.
And because it's complex to implement, my vote is to punt on this until we
have a really good reason.

That being said, it'd be smart of us [me] to document that if you want to
download `image` but only play with `image[idx]`, you should just download
`idx` until you need the rest. Onus is on the python-writer to not download
TB of data indiscriminately, because ndio _is_ the tool you'd use to
download TB of data intentionally.

**Comment by jovo** [comment]
right, "lazy". i knew that was the right word.
just something to think about.

**Comment by j6k4m8** [comment]
i think this is a #wontfix, at least for now... good to talk about for a future iteration that treats data differently — perhaps ndioR... thoughts?

**Comment by wrgr** [comment]
closing for now.  out of scope for this go around certainly.

**Comment by jovo** [comment]
maybe just add a default?

On Tue, Feb 23, 2016 at 9:04 AM, William Gray notifications@github.com
wrote:

> Closed #5 https://github.com/neurodata/ndio/issues/5.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/neurodata/ndio/issues/5#event-561665266.

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by wrgr** [comment]
@jovo - what do you mean by a default?  I'll be up in a bit to chat if you like.

**Comment by j6k4m8** [comment]
``` python
import ndio.remote.neurodata as ND
nd = ND()

nd.get_roi('kasthuri11')

# or optionally, if you know the name of the ROI you want
# (from LIMS):
nd.get_roi('kasthuri11', 'cell2015-fig4')
```

Is this adequate to close this issue? If so, it'll be in the next ndio release :)

**Comment by jovo** [comment]
yup

On Tue, Feb 23, 2016 at 11:37 AM, Jordan Matelsky notifications@github.com
wrote:

> import ndio.remote.neurodata as ND
> nd = ND()
> 
> nd.get_roi('kasthuri11')
> 
> # or optionally, if you know the name of the ROI you want# (from LIMS):
> 
> nd.get_roi('kasthuri11', 'cell2015-fig4')
> 
> Is this adequate to close this issue? If so, it'll be in the next ndio
> release :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/neurodata/ndio/issues/5#issuecomment-187780392.

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by j6k4m8** [comment]
https://github.com/neurodata/ndio-demos/blob/master/LIMS/LIMS%20ROIs.ipynb :)
