### ISSUE TITLE
Post/Get from Time Series Data

### ISSUE THREAD

**Issue by wrgr** [openconnectome/ndio#58]
Does this functionality exist?  Can we have an example?  This would enable large scale MR data uploads!!!

Realized after meeting discussion this AM that we don't need a nifti service urgently (although would be a great convenience) if we can just manually unpack and put in db with RAMONVolumes.

@gkiar @jovo

**Comment by jovo** [comment]
yes! @j6k4m8 and @Aeusman put it into ndio. it is in auto-ingest.
create new issue about that if it doesn't work for you?

**Comment by Aeusman** [comment]
@willgray can I close this?

**Comment by j6k4m8** [comment]
i don't think this exists..?

**Comment by Aeusman** [comment]
Ingesting time series exists, getting does not to my knowledge @kunallillaney confirm?

**Comment by j6k4m8** [comment]
Removing tags since they don't make sense — we need to talk more about how this interfaces with ndstore.

**Comment by wrgr** [comment]
great - let's talk - this is gonna be part of the MR work, so i vote hold a week.

**Comment by Aeusman** [comment]
Timeseries is being added because of eventual image deprecation, closing in favor of that issue.
