### ISSUE TITLE
Get fields/Put fields

### ISSUE THREAD

**Issue by wrgr** [openconnectome/ndio#59]
Does get fields work? 

This would be a big help as well for efficiently writing manual filter queries.

@jovo

**Comment by j6k4m8** [comment]
getting fields is about as expensive time-wise as getting the whole metadata (or, if you're getting cutout, the metadata is obviously negligible overhead). currently just using something like 

``` python
ndio.get_ramon( . . . , metadata_only=True).confidence
```

is your best bet until this is implemented, which may be never, depending on if `getField` is _actually_ more performant

**Comment by j6k4m8** [comment]
@kunallillaney do you have an endpoint for this?

**Comment by Aeusman** [comment]
Docs are [here](http://docs.neurodata.io/ndstore/api/ramon_api.html)

**Comment by Aeusman** [comment]
This functionality exists, but is not pretty. Happy to re-open issue but will need more information.
