### ISSUE TITLE
Filter ramon object 

### ISSUE THREAD

**Issue by wrgr** [openconnectome/ndio#64]
nd.get_ramon(token, channel, ids=idList, filter, metaOnly=True)

{true, false} = filter(ramonObj, conditional)

**Comment by j6k4m8** [comment]
see #65

**Comment by j6k4m8** [comment]
available in ndio>=0.1.8 :)

**Comment by wrgr** [comment]
w00t - this is amazing. truly.  science resuming!

**Comment by kunallillaney** [comment]
"stopping science" == @willgray not happy

**Comment by jovo** [comment]
:+1:
