### ISSUE TITLE
AutoIngest Better User Handling

### ISSUE THREAD

**Issue by Aeusman** [openconnectome/ndio#69]
Front End:
- [x] Info on token
- [ ] Check x,y imagesize
- [x] Path
- [x] Special Character checking for channels/tokens/datasets/projects
- [x] Return Message (regardless of error)

Docs:
- [x] Better explanation for offset.
- [x] URL structure?
- [x] Token names need to be unique

**Comment by Aeusman** [comment]
Turns out we run into the same problem as for the challenge data, opening tiffs and pngs in python is inconsistent at best, so I'm not sure how we are going to consistently check x,y imagesize. @kunallillaney @jovo Might make sense to drop this priority till that issue is solved. 

Alternatively I can write a (very) large series of if statements to check for data types and use separate packages for each. We will be importing a lot of libraries then, and generally its better to avoid that

**Comment by wrgr** [comment]
Why not just have a couple supported formats?  Like png and tiff for example?  

I realize I'm jumping into this late, but seems like we could either enforce types or say type checking is only done for these, and otherwise you are in "expert mode"

**Comment by jovo** [comment]
@willgray tl;dr.

@Aeusman let's talk tomorrow, i think adding support for numpy arrays seems like it might be easiest?

**Comment by Aeusman** [comment]
The challenge is not in the file types, but the data types (unit8, unit16, etc.) unit16 for example is not supported properly in any almost python imaging library (without turning it into uint8 in the process or ascribing weird windowing rules (scikit)).

**Comment by jovo** [comment]
yah, that's why i'm thinking convert everything to numpy arrays, so we don't have to deal with image types not supporting data types.  everything should be converable to an numpy array, right? 
if i'm missing something, let's G+...

**Comment by Aeusman** [comment]
@jovo support for ingesting numpy arrays exists in the 'Create Dataset/Project/Token in Console, Create Channel with ndio, Upload to channel with ndio' path, it is admittedly not straightforward. Plus you run into the same issue if you want to open an image file and convert to numpy arrays. 

@willgray see above

**Comment by jovo** [comment]
> it is admittedly not straightforward.

right.

> Plus you run into the same issue if you want to open an image file and convert to numpy arrays.

right.  

auto-ingest should support both.  then you won't need to convert to 16-bit tiff from numpy for challenge data, and if people already have tiffs/pngs in a reasonable format, you also won't need to convert.

**Comment by Aeusman** [comment]
@kunallillaney would have to add that functionality to autoingest in the backend, I'm going to pull in the other improvements made into ndio. Lets talk about this tomorrow (I'm around after 3) or Wednesday.

**Comment by jovo** [comment]
right.
i'm in class 3-4:30, then heading home,
wednesday i'm free basically all afternoon.

On Mon, Feb 15, 2016 at 8:03 PM, Alex Eusman notifications@github.com
wrote:

> @kunallillaney https://github.com/kunallillaney would have to add that
> functionality to autoingest in the backend, I'm going to pull in the other
> improvements made into ndio. Lets talk about this tomorrow (I'm around
> after 3) or Wednesday.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/neurodata/ndio/issues/69#issuecomment-184461694.

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by kunallillaney** [comment]
@jovo @Aeusman Let's talk more tomorrow. I think we are unnecessarily complicating this.

**Comment by jovo** [comment]
i was hoping you would say that :)
swing by in the afternoon?

On Tue, Feb 16, 2016 at 11:12 AM, Kunal Lillaney notifications@github.com
wrote:

> @jovo https://github.com/jovo @Aeusman https://github.com/Aeusman
> Let's talk more tomorrow. I think we are unnecessary complicating this.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/neurodata/ndio/issues/69#issuecomment-184749434.

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by kunallillaney** [comment]
@jovo So I think this is resolved now after I had a talk with @Aeusman. He can now determine x,y image sizes on images.

**Comment by j6k4m8** [comment]
ndio supports importing both numpy arrays and images from disk — which means we natively support the `numpy.shape` call to get image-size... just want to make sure we're not duplicating effort here

**Comment by j6k4m8** [comment]
closing this in light of the upcoming rewrite to use neurodata more extensively
