### ISSUE TITLE
give jovo kasthuri graph :)

### ISSUE THREAD

**Issue by jovo** [openconnectome/ndio#7]

**Comment by j6k4m8** [comment]
Waiting on:
- [ ] https://github.com/openconnectome/open-connectome/issues/181

Then,
- [ ] `ramonsegment.get_sibling_segments()`
- [ ] `ramonsegment.get_synapse_targets()`

**Comment by wrgr** [comment]
I can show you what we do for the cajal version - it's a little different/cleaner.  Back on 1/4!

**Comment by wrgr** [comment]
Done as part of claims and closed in other issues.

**Comment by wrgr** [comment]
@j6k4m8 - your helper functions you describe above would be great.  But we can do via more verbose code now.
