### ISSUE TITLE
add nifti support 

### ISSUE THREAD

**Issue by wrgr** [openconnectome/ndio#76]
recommend nibabel

We should support the following cases:
- single slice
- volume
- uint8 (possibly others)
- easy for now is great - we can extend

mana+python needs this as does d2g (aka ndmg) data upload.

**Comment by j6k4m8** [comment]
@gkiar were you looking at this potentially..? or was that stuff for elsewhere?

**Comment by wrgr** [comment]
I will PR this in a bit.

the ndmg mri upload stuff has several parts - greg is standardizing formats.  We're fixing the compatibility layer, and then together we will write an "ingest" script, perhaps as part of ndmg or autoingest or ndio...

**Comment by wrgr** [comment]
this is done.  Will make a followup to support ndmg specific needs.
