### ISSUE TITLE
convert enumerations into human readable format (the enumeration)

### ISSUE THREAD

**Issue by wrgr** [openconnectome/ndio#78]
Add capability to convert enumerated value to enumeration

**Comment by j6k4m8** [comment]
This is (apparently!) fixed in json :)

**Comment by wrgr** [comment]
waiiiit - what do you mean?  if working, post a quick example here?

**Comment by j6k4m8** [comment]
http://openconnecto.me/ocp/ca/kasthuri2015_ramon_v4/neurons/3/json/

`type` is already a string now — unless you want enums for the segment class etc, which will be a much longer-term fix
