### ISSUE TITLE
add blosc interface option 

### ISSUE THREAD

**Issue by wrgr** [openconnectome/ndio#85]
to start, just needs to work with getting raw image data. 

We need to talk about how to decouple metadata and image data, but separate issue for that - let's get through this first.

**Comment by j6k4m8** [comment]
did you say you'd be cool with implementing this? I won't have time to do this for a little bit, but I'm happy to merge in a PR :)

**Comment by wrgr** [comment]
yea - kunal and I are taking care of this as a PR.  
need you urgently to discuss doing this as an in-memory operation vs. saving to disk.  Not much advantage do saving to disk.  Only bad afaict, except possibly scraping.  Maybe a flag in get_volume where in memory uses blosc?  

@kunallillaney

**Comment by kunallillaney** [comment]
@willgray I pushed the convert blosc.py file. All yours.

**Comment by wrgr** [comment]
A little help?  

Two questions:  
- blosc returns a 4D array, so a slice is im = [1,1,X,Y].  We usually use 3D arrays, so for compatibility, I take only the first slice of the first dimension, e.g., im[0].  Seems ok to me?
- the vanilla `import blosc` passes all tests for python 2.7.x, but [fails for 3.x](https://travis-ci.org/neurodata/ndio/jobs/110604365).  Any ideas?  There is a python-blosc package but I am out of time to investigate further.

Otherwise [this](https://github.com/neurodata/ndio/tree/blosc-download) is ready to merge!

@kunallillaney @gkiar @j6k4m8 @alexbaden

**Comment by kunallillaney** [comment]
@willgray The 4-d array is as follows: [channel, z, y, x]. There is a blosc package for 3.x but not sure what your build process looks like.

**Comment by wrgr** [comment]
@kunallillaney [channel, z, y, x]?  Or [channel, z, x, y]?

I see - ndio currently only permits one channel, so my current slicing seems like the right answer.

Is there a blosc package that works for 2.x and 3.x?  I see several packages out there, but don't know what's good.  So far, all ndio imports work with both 2.x and 3.x

**Comment by kunallillaney** [comment]
[Here](https://github.com/Blosc/python-blosc) is the package I use and it is supported for python 3.x. The order is what I mentioned, why would we do z,x,y(this is not Matlab)

**Comment by wrgr** [comment]
Lol - yea, trying to standardize the code base and there's some discrepancy in how arrays are interpreted.

We are using python-blosc - any thoughts on why we pass 2.7 tests but not 3.x tests?  Link to test build upthread.

**Comment by wrgr** [comment]
This is my blosc command:

`blosc.unpack_array(req.content)[0]`

Where req.content is the data returned from the restful call.

**Comment by j6k4m8** [comment]
see #97! we actually mandate blosc when available — it's pretty clearly superior.
