### ISSUE TITLE
create jupyter notebook for downloading example data

### ISSUE THREAD

**Issue by wrgr** [openconnectome/ndio#9]
Create jupyter notebook allowing for easy download and format conversion for sample datasets across different formats.

Proposed use case (I get it, I think!):
- User says get_reference_data('ac3', 'png')

Notebook will use preconfigured server, token, channel, cutout arg settings to setup 'remote' and 'query', download data, and output in the requested format.

Preconfigured parameters will exist in the notebook (?) as switch statements, unless we come up with something more clever.

Yes?

**Comment by wrgr** [comment]
All capability to do this exists now...just need to do it.

**Comment by jovo** [comment]
:+1:

**Comment by j6k4m8** [comment]
if someone can get me ROIs for each token that we want to provide, I'll write these up!

**Comment by jovo** [comment]
ac3 & ac4 would be good, though when i look at them in eg, http://viz.neurodata.io/ac4/
they look blank.

**Comment by j6k4m8** [comment]
some channels have an `ROI` in LIMS. I'll write some ndio-demos for those? Is that sufficient to define this behavior?

**Comment by jovo** [comment]
depending on the channel/ROI, yes.

**Comment by j6k4m8** [comment]
Available here: https://github.com/neurodata/ndio-demos/blob/master/LIMS/LIMS%20ROIs.ipynb (See #118 for future discussion)
