### ISSUE TITLE
include millis in ndio test suite token names

### ISSUE THREAD

**Issue by j6k4m8** [openconnectome/ndio#96]
See [this build](https://travis-ci.org/neurodata/ndio/jobs/111007863) for an example of the same token being generated in Py3 and Py2 (leading to a collision).

**Comment by Aeusman** [comment]
@j6k4m8 This is an unfortunate consequence of using a time-based name for testing, in this case the same name has overlapped it seems. I'll fix by adding version number to end.

**Comment by j6k4m8** [comment]
py version? sounds good :) though i'd still add millis, since there's still a possibility of two tests running at the same (minute) time.

**Comment by Aeusman** [comment]
If they are at same minute time the version numbers will differ so we should be good.

**Comment by Aeusman** [comment]
Fixed and pulled
