### ISSUE TITLE
autoingest tests fail

### ISSUE THREAD

**Issue by j6k4m8** [openconnectome/ndio#99]
| ndio version | os | python |
| --- | --- | --- |
| 0.1.* | * | * |

Autoingest tests are failing on <kbd>master</kbd>:
https://travis-ci.org/neurodata/ndio/jobs/111034163#L1128

**Comment by Aeusman** [comment]
For some reason requests to the aws server are timing out with 504. Investigating

**Comment by j6k4m8** [comment]
any word on this? it's killing all our tests :(

**Comment by wrgr** [comment]
@kunallillaney - any ideas here?

**Comment by j6k4m8** [comment]
This is becoming a priority because it's delaying test-suite completion by ≈10m, which delays merges... Should I just delete these tests, @Aeusman?

**Comment by wrgr** [comment]
Comment out these tests for now.  @Aeusman - if we are going to leave this code in ndio, we need to never break master, please!

@jovo

**Comment by kunallillaney** [comment]
@willgray @j6k4m8 Comment them out for now. I will talk with @Aeusman and see what his tests consist of and to make them better.

**Comment by j6k4m8** [comment]
On the backburner, commented in #116.
